### ISSUE TITLE
name 'convert_yaml_to_list' is not defined

### ISSUE THREAD

**Issue by SebastianSchildt** [GENIVI/vss-tools#15]
No matter waht I do, with current tools I can not generate anything, not even the CSV example

```
$ python3 ./vspec2csv.py -i:../spec/VehicleSignalSpecification.id ../spec/VehicleSignalSpecification.vspec vss.csv
Traceback (most recent call last):
  File "./vspec2csv.py", line 97, in <module>
    tree = vspec.load_tree(args[0], include_dirs)
  File "/home/sebastian/vehicle_signal_specification/vss-tools/vspec.py", line 225, in load_tree
    flat_model = load_flat_model(file_name, "", include_paths)
  File "/home/sebastian/vehicle_signal_specification/vss-tools/vspec.py", line 316, in load_flat_model
    raw_yaml = convert_yaml_to_list(raw_yaml)
NameError: name 'convert_yaml_to_list' is not defined
```

Any pointers @floix @gunnarx ?

**Comment by SebastianSchildt** [comment]
@danielwilms

**Comment by danielwilms** [comment]
@SebastianSchildt same here, I'll have a look.
